name: Continuous E2E Changing Working Quorum Test With High Load

permissions:
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  ### Please remember to use different namespace for different tests
  # Performance test in an optimal setting
  check-repo: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/check-aptos-core
        with:
          cancel-workflow: true

  run-forge-changing-working-quorum-test-high-load:
    needs: check-repo
    uses: aptos-labs/aptos-core/.github/workflows/workflow-run-forge.yaml@main
    secrets: inherit
    with:
      FORGE_NAMESPACE: forge-changing-working-quorum-test-high-load
      FORGE_RUNNER_DURATION_SECS: 900
      FORGE_TEST_SUITE: changing_working_quorum_test_high_load
      POST_TO_SLACK: true
      FORGE_ENABLE_FAILPOINTS: true
