name: Continuous E2E Network Partition Test

permissions:
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  check-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/check-aptos-core
        with:
          cancel-workflow: true

  run-forge-network-partition-test:
    needs: check-repo
    uses: aptos-labs/aptos-core/.github/workflows/workflow-run-forge.yaml@main
    secrets: inherit
    with:
      FORGE_NAMESPACE: forge-network-partition
      # Run for 15 minutes
      FORGE_RUNNER_DURATION_SECS: 900
      FORGE_TEST_SUITE: network_partition
      POST_TO_SLACK: true
