name: Continuous E2E Compat Test

permissions:
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  check-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/check-aptos-core
        with:
          cancel-workflow: true

  run-forge-compat:
    needs: check-repo
    uses: aptos-labs/aptos-core/.github/workflows/workflow-run-forge.yaml@main
    secrets: inherit
    with:
      FORGE_NAMESPACE: forge-compat
      # Run for 5 minutes
      FORGE_RUNNER_DURATION_SECS: 300
      # This will upgrade from testnet branch to the latest main
      FORGE_TEST_SUITE: compat
      IMAGE_TAG: testnet
      POST_TO_SLACK: true
