name: Continuous E2E Validator Reboot Stress Test

permissions:
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  check-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/check-aptos-core
        with:
          cancel-workflow: true

  run-forge-validator-reboot-stress-test:
    needs: check-repo
    uses: aptos-labs/aptos-core/.github/workflows/workflow-run-forge.yaml@main
    secrets: inherit
    with:
      FORGE_NAMESPACE: forge-validator-reboot-stress
      # Run for 40 minutes
      FORGE_RUNNER_DURATION_SECS: 2400
      FORGE_TEST_SUITE: validator_reboot_stress_test
      POST_TO_SLACK: true
